### ISSUE TITLE
Material Help?

### ISSUE THREAD

**Issue by ItsJustSub** [BL2CP/BLCMods#103]
Hey, guys, very new to the modding thing and wanted some help with making materials! I'm currently making a "#Gold" series of weapons which are just stupid-op souped up versions of weapons from Borderlands 1, and I need help making the materials just plain-ass gold.  Any help will be appreciated ty.

**Comment by 00Schmidt** [comment]
Look in daves skin nodding guide, and if that doesn't work you can find the rgb value for gold, but there's a reflective material for gold, just don't remember the name

**Comment by ItsJustSub** [comment]
wow I'm stupid.  I spent like 2 hours trying to find his guide last night and I get on for 5 minutes just now and find it. Thank you!
