### ISSUE TITLE
Modding skill trees

### ISSUE THREAD

**Issue by FluxedUpGaming** [BL2CP/BLCMods#117]
Hi. I'm new to modding and want to start by changing how some of Gaige's skills work. But I have know idea how. Can anyone with more experience help me out?

**Comment by MagicGonads** [comment]
Please ask the people on the discord https://discordapp.com/invite/0YjZxbVBS9b3bXUS

The issues section should be for specific questions of particular relevance to content on this github, not general inquiry.
