### ISSUE TITLE
Borderlands TPS

### ISSUE THREAD

**Issue by Kiesuks** [BL2CP/BLCMods#49]
Hello, 

Firstly, I would like to thank you all for such an amazing work with mods and patches. The main reason I'm writing this is that I have issue with BTPS patch, after reading patchnotes I knew I must have it, but the problem is after I hex edit BorderlandsPreSequel.exe (I change hex code "83C40C85C0751A6A" to "83C40C85FF751A6A and text string's numbers "730061007900" to "000000000000") the game on lauch gives me this error "The application was unable to start correctly (0xc0000nnn). Click OK to close the application." I have hex edited and applied patch for my BL2 game and it works perfectly.

Sorry if this isn't the right place to post this issue. I have for two days tried to look up this problem myself, but wasn't able to solve it. 

Thanks.

**Comment by KuroPanther** [comment]
Hey o/ delete your BLTPS launcher, go on steam and verify the games files (steam will download a new launcher and any missing file), then hex edit again, maybe this solves your problems.

**Comment by Kiesuks** [comment]
@KuroPanther 
Thanks for replying it seems that this problem is caused by "Reloaded" cracked launcher, exe and steamapi.dll. (Yes, I tried to patch it on cracked version). But since I have bought BLTPS on steam, just without "Claptastic Voyage", I'm going to try to patch it on legal version.

**Comment by Edd33rd** [comment]
for all pre-cracked pre-sequel games,just take laucher out of game file and leave in safe place then hex editer the .exe that has name of game.then just lauch the game with the .exe file you hex edited you don't even need the cracked launcher in the game file for the game to run and now you can use community mods on pre-cracked games without going to steam and downloading any files have fun

**Comment by GraciousPup** [comment]
@Edd33rd 
Does make it so that the patch will work on a cracked version of the game?
