### ISSUE TITLE
BLC Mods and Linux

### ISSUE THREAD

**Issue by Zbradaradjan** [BL2CP/BLCMods#54]
Hi, I'd like to know if there's a way to install them on a Linux installed game. Not going through wine, since it was ported. I tried but am not very knowledgeable and it didn't work.
Thanks !

**Comment by Lukaboot** [comment]
Go to ~/.local/share/Steam/steamapps/common/Borderlands2/steamassets/willowgame/coockedpcconsole or something similar on Mac
rename engine.upk and engine.upk.uncompressed_size to something else or move it from this directory
Place patched engine.upk to this directory
Place patch.txt to ~/.local/share/Steam/steamapps/common/Borderlands 2/steamassets/binaries directory (you can find it on craig video, but I uploaded patch to my repository and will update it when new patch will come, so you can always have the latest version in one url, here it is). Also keep in mind that linux version of the game doesn't see files with upper case, so you need to name it patch.txt, not Patch.txt
Bind a console hotkey, edit ~/.local/share/aspyr-media/borderlands 2/willowgame/config/willowinput.ini file, search for ConsoleKey=Undefine and change it to ConsoleKey=Tilde (or any other button, F6 for example)

While on main menu, press esc and confirm exit to start screen. Then open console and type exec patch.txt.


---- thats it

**Comment by Zbradaradjan** [comment]
Alright, I'm trying this, thanks.
